# This is a basic workflow to help you get started with Actions

name: Linting

env:
  node-version: 15.x


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  eslint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - run: npm ci
    - uses: bradennapier/eslint-plus-action@v3.4.2
      with:
        configFile: .eslintrc.js
        includeGlob: ./src/**/*.ts
